[package]
name = "OverUnder-63264A"
version = "0.1.0"
authors = ["Ethan Wu", "Jacob Signorovitch"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.vex-rt]
vex-rt = "0.15.1"
version = "0.15.1"
